# This code is generated by ChatGPT

import xml.etree.ElementTree as ET
from collections import Counter

tree = ET.parse("src/mini/PFC_mini_74xx.circ")
root = tree.getroot()

def count_74xx_in_circuit(circuit_element):
    counter = Counter()
    for comp in circuit_element.iter("comp"):
        name = comp.get("name", "")
        if name.startswith("74"):
            counter[name] += 1
        if name.startswith("TTL_"):
            name = name[4:]
            counter[name] += 1
        if name.startswith("CD"):
            name = name[2:]
            counter[name] += 1
    return counter

circuits = {}

for circuit in root.iter("circuit"):
    cname = circuit.get("name")
    circuits[cname] = circuit

main = circuits.get("main")
if main is None:
    raise RuntimeError("No main circuit found.")

main_74xx = count_74xx_in_circuit(main)

subcircuit_instance_counts = Counter()

for comp in main.iter("comp"):
    name = comp.get("name")
    if name in circuits and name != "main":
        subcircuit_instance_counts[name] += 1

subcircuits_74xx = {
    cname: count_74xx_in_circuit(circ)
    for cname, circ in circuits.items()
    if cname != "main"
}

expanded_74xx = Counter(main_74xx)

for cname, instance_count in subcircuit_instance_counts.items():
    for part, cnt in subcircuits_74xx[cname].items():
        expanded_74xx[part] += cnt * instance_count

print("74xx inside MAIN circuit")
for part, cnt in main_74xx.items():
    print(f"  {part}: {cnt}")

print("\nSubcircuit instance counts inside MAIN")
for cname, cnt in subcircuit_instance_counts.items():
    print(f"  {cname}: {cnt}")

print("\n74xx inside each subcircuit (one instance)")
for cname, counter in subcircuits_74xx.items():
    print(f"  {cname}:")
    for part, cnt in counter.items():
        print(f"    {part}: {cnt}")

print("\nFINAL total 74xx counts (expanded)")
keys = list(expanded_74xx.keys())
keys.sort(key=lambda x: int(x))
for part in keys:
    print(f"  {part}, {expanded_74xx[part]}")